package com.mycompany.cattleshuffle.Windows;
import javax.swing.JOptionPane;
import com.mycompany.cattleshuffle.Classes.AnimalFattening;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import com.mycompany.cattleshuffle.Classes.*;
import java.io.*;

public class AddAnimalProducer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddAnimalProducer.class.getName());
    private double age;
    private String product;
    private String name;
    private String tag;
    private boolean verify = true;
    private String Species ="Vaca";
    private double weight =350.2;
    private AnimalProducer newAnimal;
    public static final Path PRODUCER_PATH = Paths.get("data/animals/producer.json");
    public AddAnimalProducer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        animalAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        animalProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        animalName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        animalTag = new javax.swing.JTextField();
        saveAnimal = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        animalWeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        animalSpecie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(101, 178, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Agregar nuevo animal de producción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        jPanel2.setBackground(new java.awt.Color(204, 229, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Edad (meses):");

        animalAge.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        animalAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalAgeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Producto:");

        animalProduct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        animalProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalProductActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Nombre:");

        animalName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("ID");

        animalTag.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        animalTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalTagActionPerformed(evt);
            }
        });

        saveAnimal.setBackground(new java.awt.Color(255, 153, 153));
        saveAnimal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        saveAnimal.setText("Guardar registro");
        saveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAnimalActionPerformed(evt);
            }
        });

        mainButton.setBackground(new java.awt.Color(153, 255, 153));
        mainButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        mainButton.setText("Regresar al menú animal");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Peso:");

        animalWeight.setBackground(new java.awt.Color(255, 255, 255));
        animalWeight.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        animalWeight.setForeground(new java.awt.Color(0, 0, 0));
        animalWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalWeightActionPerformed(evt);
            }
        });

        jLabel6.setText("Especie:");

        animalSpecie.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        animalSpecie.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(animalAge)
                            .addComponent(animalProduct)
                            .addComponent(animalName)
                            .addComponent(animalWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(animalSpecie, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(animalTag, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(mainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveAnimal)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(animalAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(animalWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(animalProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(animalSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(animalTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainButton)
                    .addComponent(saveAnimal))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        // TODO add your handling code here:
        AnimalType ventana = new AnimalType();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mainButtonActionPerformed

    private void animalTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalTagActionPerformed
        try{
            this.tag = animalTag.getText().trim();
            System.out.println(this.tag);  
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_animalTagActionPerformed

    private void saveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAnimalActionPerformed
    try{
            double age = Double.parseDouble(animalAge.getText());
            String product = animalProduct.getText().trim();
            String name = animalName.getText().trim();
            String tag = animalTag.getText().trim();
            
            if(name.isEmpty()){
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío");
                return;
            }
            AnimalProducer animal = new AnimalProducer("none","none",(int)0, "none",0);
            animal.setName(name);
            animal.setWeight(weight);
            animal.setTag(tag);
            animal.setProducto(product);
            animal.setAge((int)age);
            animal.setSpecies(Species);
            
            List<AnimalProducer> producer = FileManager.loadProducers(PRODUCER_PATH);
            producer.add(animal);
            FileManager.saveProducers(producer, PRODUCER_PATH);
            
            JOptionPane.showMessageDialog(this, "Animal de engorde registrado correctamente");
            
            animalAge.setText("");
            animalWeight.setText("");
            animalName.setText("");
            animalTag.setText("");
            animalProduct.setText("");
            animalSpecie.setText("");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error, debes usar números válidos para edad y peso");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error inesperado" + e.getMessage());
        }
    }//GEN-LAST:event_saveAnimalActionPerformed

    private void animalAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalAgeActionPerformed
        try{
            this.age = Double.parseDouble(animalAge.getText().trim());
            System.out.println(this.age);  
        } catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_animalAgeActionPerformed

    private void animalProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalProductActionPerformed
        try{
            this.product = animalProduct.getText().trim();
            System.out.println(this.product);  
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_animalProductActionPerformed

    private void animalWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalWeightActionPerformed
        try{
            this.weight = Double.parseDouble(animalWeight.getText().trim());
            System.out.println(this.weight);  
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_animalWeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddAnimalProducer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField animalAge;
    private javax.swing.JTextField animalName;
    private javax.swing.JTextField animalProduct;
    private javax.swing.JTextField animalSpecie;
    private javax.swing.JTextField animalTag;
    private javax.swing.JTextField animalWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mainButton;
    private javax.swing.JButton saveAnimal;
    // End of variables declaration//GEN-END:variables
}
