package com.mycompany.cattleshuffle.Windows;
import com.mycompany.cattleshuffle.Classes.AnimalBreeder;
import com.mycompany.cattleshuffle.Classes.AnimalFattening;
import com.mycompany.cattleshuffle.Classes.AnimalProducer;
import com.mycompany.cattleshuffle.Classes.FileManager;
import java.awt.Color;
import java.nio.file.Paths;
import java.nio.file.Path;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.List;

public class Filter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Filter.class.getName());
    private final Path breedersPath = Paths.get("data/animals/breeders.json");
    private final Path producerPath = Paths.get("data/animals/producer.json");
    private final Path fatteningPath = Paths.get("data/animals/fattening.json");
    
    public Filter() {
        initComponents();
        
        idAnimal.setText("Buscar");
        idAnimal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        idAnimal.setForeground(Color.BLACK);  
        
        idAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt){
                if(idAnimal.getText().equals("Buscar")){
                    idAnimal.setText("");
                    idAnimal.setForeground(Color.BLACK);
                }
            }
            
            @Override
            public void focusLost(java.awt.event.FocusEvent evt){
                if(idAnimal.getText().trim().isEmpty()){
                    idAnimal.setText("Buscar");
                    idAnimal.setForeground(Color.BLACK);
                }
            }
            
        });
        
        resultsText.setText("Resultados: ");
        resultsText.setEditable(false);

        SwingUtilities.invokeLater(() -> {
        idAnimal.setText("Buscar");
        idAnimal.setForeground(Color.BLACK);
        });   
        
        SwingUtilities.invokeLater(() -> {
            jPanel1.requestFocusInWindow();
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultsText = new javax.swing.JTextArea();
        selectButton = new javax.swing.JButton();
        typeFilter = new javax.swing.JComboBox<>();
        filterButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Filtro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 60));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("ID Animal:");

        idAnimal.setBackground(new java.awt.Color(153, 204, 255));
        idAnimal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        idAnimal.setText("Buscar");
        idAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAnimalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Registros totales");

        resultsText.setColumns(20);
        resultsText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        resultsText.setRows(5);
        jScrollPane2.setViewportView(resultsText);

        selectButton.setBackground(new java.awt.Color(153, 204, 255));
        selectButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        selectButton.setText("Seleccionar todos");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        typeFilter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        typeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Producción de bienes", "Reproducción", "Engorde" }));
        typeFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFilterActionPerformed(evt);
            }
        });

        filterButton.setBackground(new java.awt.Color(153, 204, 255));
        filterButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        filterButton.setText("Filtrar");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        mainButton.setBackground(new java.awt.Color(153, 255, 153));
        mainButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        mainButton.setText("Regresar al menú ");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(153, 255, 153));
        registerButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(0, 0, 0));
        registerButton.setText("Registrar");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(registerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(typeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)
                            .addComponent(filterButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(184, 184, 184)
                            .addComponent(idAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectButton))
                    .addComponent(jScrollPane2))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainButton)
                    .addComponent(registerButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAnimalActionPerformed
        // TODO add your handling code here:
        String id = idAnimal.getText().trim();
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Porfavor ingresa un ID de animal","Advertencia", JOptionPane.WARNING_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(this, "Buscando un animal con ID: " + id);
        }
    }//GEN-LAST:event_idAnimalActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        StringBuilder sb = new StringBuilder("Todos los animales registrados:\n");

    try {
        // Cargar de producción
        List<AnimalProducer> producers = FileManager.loadProducers(producerPath);
        for (AnimalProducer a : producers) {
            sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Producer\n");
        }

        // Cargar de crianza
        List<AnimalBreeder> breeders = FileManager.loadBreeders(breedersPath);
        for (AnimalBreeder a : breeders) {
            sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Breeder\n");
        }

        // Cargar de engorde
        List<AnimalFattening> fattenings = FileManager.loadFattening(fatteningPath);
        for (AnimalFattening a : fattenings) {
            sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Fattening\n");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error cargando los animales: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    resultsText.setText(sb.toString());
        
    }//GEN-LAST:event_selectButtonActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        String idSearch = idAnimal.getText().trim();
        String typeSelected = (String) typeFilter.getSelectedItem();

        StringBuilder sb = new StringBuilder("Resultados:\n");
        String id = idAnimal.getText().trim();
        if(id.isEmpty() || id.equalsIgnoreCase("Buscar")){
            JOptionPane.showMessageDialog(this, "Debes escribir un ID válido para buscar el animal.");
            return;
        }
        try {
        // PRODUCER
        if (typeSelected.equals("Tipo") || typeSelected.equals("producción de bienes")) {
            List<AnimalProducer> producer = FileManager.loadProducers(producerPath);
            System.out.println("Producers cargados: " + producer.size());
            for (AnimalProducer a : producer) {
                if (idSearch.equals("Buscar") || idSearch.isEmpty() || a.getTag().equalsIgnoreCase(idSearch)) {
                    
                    sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Producer\n");
                }
            }
        }
        if (typeSelected.equals("Tipo") || typeSelected.equals("Reproducción")) {
            List<AnimalBreeder> breeders = FileManager.loadBreeders(breedersPath);
            for (AnimalBreeder a : breeders) {
                if (idSearch.equals("Buscar") || idSearch.isEmpty() || a.getTag().equalsIgnoreCase(idSearch)) {
                    sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Breeder\n");
                }
            }
        }
        // FATTENING
        if (typeSelected.equals("Tipo") || typeSelected.equals("Engorde")) {
            List<AnimalFattening> fattenings = FileManager.loadFattening(fatteningPath);
            for (AnimalFattening a : fattenings) {
                if (idSearch.equals("Buscar") || idSearch.isEmpty() || a.getTag().equalsIgnoreCase(idSearch)) {
                    sb.append(a.getTag()).append(" - ").append(a.getName()).append(" - Fattening\n");
                }
            }
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error cargando los animales: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        resultsText.setText(sb.toString());

    }//GEN-LAST:event_filterButtonActionPerformed

    private void typeFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFilterActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        // TODO add your handling code here:
        MainMenu ventana = new MainMenu();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mainButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
  
        try{
        List<AnimalProducer> producers = FileManager.loadProducers(producerPath);
        List<AnimalBreeder> breeders = FileManager.loadBreeders(breedersPath);
        List<AnimalFattening> fattenings = FileManager.loadFattening(fatteningPath);
        
        for(AnimalProducer a : producers){
                new RegisterProducts(a).setVisible(true);
                this.dispose();
                return;
          
        }
        for(AnimalBreeder a : breeders){
                new RegisterBreeders(a).setVisible(true);
                this.dispose();
                return;
            
        }
        
        for(AnimalFattening a : fattenings){
                new RegisterFattening(a).setVisible(true);
                this.dispose();
                return;
        }
        
        JOptionPane.showMessageDialog(this, "No se encontró ningún animal con ese ID.");

        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al abrir ventana: " + e.getMessage());
        }

    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Filter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filterButton;
    private javax.swing.JTextField idAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mainButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextArea resultsText;
    private javax.swing.JButton selectButton;
    private javax.swing.JComboBox<String> typeFilter;
    // End of variables declaration//GEN-END:variables
}
