
package com.mycompany.cattleshuffle.Windows;

import com.mycompany.cattleshuffle.Classes.AnimalBreeder;

public class RegisterBreeders extends javax.swing.JFrame {
    private AnimalBreeder animal;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterBreeders.class.getName());

    /**
     * Creates new form RegisterBreeders
     */
    public RegisterBreeders(AnimalBreeder animal) {
        initComponents();
        this.animal = animal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
