package com.mycompany.cattleshuffle.Windows;
import com.mycompany.cattleshuffle.Classes.AnimalFattening;

public class RegisterFattening extends javax.swing.JFrame {
    private AnimalFattening animal;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFattening.class.getName());

    /**
     * Creates new form RegisterFattening
     */
    public RegisterFattening(AnimalFattening animal) {
        initComponents();
        this.animal = animal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
